export const SAVE_ORDER = "SAVE_ORDER";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const SET_SELECTED_ADDRESS = "SET_SELECTED_ADDRESS";
export const UPDATE_COUPON = "UPDATE_COUPON";
