export const SET_SIGNUP_EMAIL_ERROR = "SET_SIGNUP_EMAIL_ERROR";
export const SET_SIGNUP_FULLNAME_ERROR = "SET_SIGNUP_FULLNAME_ERROR";
export const SET_SIGNUP_PASSWORD_ERROR = "SET_SIGNUP_PASSWORD_ERROR";
export const SET_SIGNUP_FORM_ERROR = "SET_SIGNUP_FORM_ERROR";
export const SET_SIGNUP_CONFIRM_PASSWORD_ERROR =
  "SET_SIGNUP_CONFIRM_PASSWORD_ERROR";
export const CLEAR_SIGNUP_FORM = "CLEAR_SIGNUP_FORM";
