import uuid from "react-uuid";

export const data = [
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "JBL Go 3",
		alt: "JBL Go 3",
		image: "https://m.media-amazon.com/images/I/81GE-JdnNMS._AC_UY218_.jpg",
		description: "Wireless Ultra Portable Bluetooth Speaker, JBL Pro Sound)",
		latestPrice: "2999.00",
		oldPrice: "3999.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall Acton II 60 ",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51Tn3qxqr3L._AC_UY218_.jpg",
		description:
			"Marshall Acton II 60 Watt Wireless Bluetooth Speaker (Black), (MRL1001900)",
		latestPrice: "5000.00",
		oldPrice: "6000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
	{
		id: uuid(),
		latest: true,
		productName: "Marshall",
		alt: "Marshall speaker",
		image: "https://m.media-amazon.com/images/I/51UYQQsQVfL._AC_UY218_.jpg",
		description: "Acton II 15 Watt Wireless Bluetooth Speaker (Black)",
		latestPrice: "1900.00",
		oldPrice: "3000.00",
	},
];
